using UnityEngine;
using YG;

public class ADSforButton : MonoBehaviour
{
    public GameObject OpenSceneFIG;
    public GameObject CloseSceneFIG;
    public GameObject CloseSceneVIR;
    public GameObject OpenSceneVIR;

// Подписываемся на событие открытия рекламы в OnEnable
private void OnEnable() => YandexGame.RewardVideoEvent += Rewarded;

// Отписываемся от события открытия рекламы в OnDisable
private void OnDisable() => YandexGame.RewardVideoEvent -= Rewarded;

// Подписанный метод получения награды
void Rewarded(int id)
{
        // Если ID = 1, то выдаём "+100 монет"
        if (id == 1)
        {
            OpenSceneFIG.SetActive(true);
            CloseSceneFIG.SetActive(false);
        }
        else if (id == 2)
        {
            OpenSceneVIR.SetActive(true);
            CloseSceneVIR.SetActive(false);
        }
    }

// Метод для вызова видео рекламы
public void ExampleOpenRewardAd(int id)
{
    // Вызываем метод открытия видео рекламы
    YandexGame.RewVideoShow(id);
}
}
